name: Release (tag -> GitHub + Zenodo)

on:
  push:
    tags:
      - 'v*'   # e.g., v1.0.0

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cffconvert for validation
        run: |
          python -m pip install --upgrade pip
          pip install cffconvert==2.*

      - name: Validate CITATION.cff
        run: |
          if [ -f CITATION.cff ]; then
            cffconvert --validate --infile CITATION.cff
          else
            echo "::warning::CITATION.cff not found; GitHub citation button will be unavailable."
          fi

      - name: Build Zenodo metadata (optional artifact)
        run: |
          echo '{ "title": "RANNTA — Mythosymbolic Fractalism (MSF)", "upload_type": "dataset", "description": "Release snapshot for Mythosymbolic Fractalism (MSF).", "creators": [{"name": "ilia144000"}], "access_right": "open" }' > zenodo.json
          echo "Built zenodo.json"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            CITATION.cff
            README.md
            LICENSE*
            zenodo.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
